/**
 * Batch Export Generator
 * Generates CSS snippets, design tokens, and other export formats
 */

import { type ColorSuggestion } from "./color-suggester";
import { type AccessibilityReport, type ContrastIssue } from "./contrast-analyzer";

export interface ExportOptions {
  format: "css" | "json" | "scss" | "tailwind" | "figma";
  includeComments: boolean;
  minify: boolean;
}

/**
 * Generate CSS snippet from color suggestions
 */
export function generateCSSSnippet(
  issues: ContrastIssue[],
  suggestions: Map<number, ColorSuggestion>,
  options: { minify?: boolean; includeComments?: boolean } = {}
): string {
  const { minify = false, includeComments = true } = options;

  let css = "";

  if (includeComments && !minify) {
    css += "/* Generated by Site Auditor Pro - Color Contrast Fixes */\n";
    css += "/* Apply these CSS rules to fix color contrast issues */\n\n";
  }

  issues.forEach((issue, index) => {
    const suggestion = suggestions.get(index);
    if (!suggestion) return;

    if (includeComments && !minify) {
      css += `/* Issue ${index + 1}: ${issue.element || "Unknown selector"} */\n`;
      css += `/* Original: ${issue.foreground} on ${issue.background} (${issue.ratio.toFixed(2)}:1) */\n`;
      css += `/* Suggested: ${suggestion.foreground} on ${suggestion.background} (${suggestion.ratio.toFixed(2)}:1) */\n`;
    }

    const selector = issue.element || "/* selector */";

    if (issue.foreground !== suggestion.foreground) {
      css += `${selector} { color: ${suggestion.foreground}; }\n`;
    }

    if (issue.background !== suggestion.background) {
      css += `${selector} { background-color: ${suggestion.background}; }\n`;
    }

    if (!minify) css += "\n";
  });

  if (minify) {
    css = css
      .replace(/\/\*.*?\*\//g, "")
      .replace(/\n\s*/g, "")
      .trim();
  }

  return css;
}

/**
 * Generate SCSS variables from suggestions
 */
export function generateSCSSVariables(
  issues: ContrastIssue[],
  suggestions: Map<number, ColorSuggestion>
): string {
  let scss = "// Generated by Site Auditor Pro - Color Contrast Fixes\n";
  scss += "// SCSS Variables for color updates\n\n";

  const colorMap = new Map<string, { original: string; suggested: string }>();

  issues.forEach((issue, index) => {
    const suggestion = suggestions.get(index);
    if (!suggestion) return;

    if (issue.foreground !== suggestion.foreground) {
      const key = `$text-color-${index + 1}`;
      colorMap.set(key, {
        original: issue.foreground,
        suggested: suggestion.foreground,
      });
    }

    if (issue.background !== suggestion.background) {
      const key = `$bg-color-${index + 1}`;
      colorMap.set(key, {
        original: issue.background,
        suggested: suggestion.background,
      });
    }
  });

  colorMap.forEach((colors, varName) => {
    scss += `// Original: ${colors.original}\n`;
    scss += `${varName}: ${colors.suggested};\n\n`;
  });

  return scss;
}

/**
 * Generate JSON design tokens
 */
export function generateDesignTokens(
  issues: ContrastIssue[],
  suggestions: Map<number, ColorSuggestion>
): string {
  const tokens = {
    version: "1.0.0",
    generated: new Date().toISOString(),
    colorContrast: {
      fixes: [] as Array<{
        id: number;
        selector: string;
        original: { foreground: string; background: string; ratio: number };
        suggested: { foreground: string; background: string; ratio: number };
        wcagLevel: string;
        improvement: number;
      }>,
    },
  };

  issues.forEach((issue, index) => {
    const suggestion = suggestions.get(index);
    if (!suggestion) return;

    tokens.colorContrast.fixes.push({
      id: index + 1,
      selector: issue.element || "unknown",
      original: {
        foreground: issue.foreground,
        background: issue.background,
        ratio: Number(issue.ratio.toFixed(2)),
      },
      suggested: {
        foreground: suggestion.foreground,
        background: suggestion.background,
        ratio: Number(suggestion.ratio.toFixed(2)),
      },
      wcagLevel: suggestion.wcagLevel,
      improvement: Number(suggestion.improvement.toFixed(1)),
    });
  });

  return JSON.stringify(tokens, null, 2);
}

/**
 * Generate Tailwind CSS config
 */
export function generateTailwindConfig(
  issues: ContrastIssue[],
  suggestions: Map<number, ColorSuggestion>
): string {
  let config = "// Generated by Site Auditor Pro - Tailwind Color Config\n";
  config += "// Add this to your tailwind.config.js colors section\n\n";
  config += "module.exports = {\n";
  config += "  theme: {\n";
  config += "    extend: {\n";
  config += "      colors: {\n";

  const colorMap = new Map<string, string>();
  let colorIndex = 1;

  issues.forEach((issue, index) => {
    const suggestion = suggestions.get(index);
    if (!suggestion) return;

    if (issue.foreground !== suggestion.foreground) {
      const colorName = `textFixed${colorIndex}`;
      colorMap.set(colorName, suggestion.foreground);
      colorIndex++;
    }

    if (issue.background !== suggestion.background) {
      const colorName = `bgFixed${colorIndex}`;
      colorMap.set(colorName, suggestion.background);
      colorIndex++;
    }
  });

  colorMap.forEach((hex, name) => {
    config += `        '${name}': '${hex}',\n`;
  });

  config += "      },\n";
  config += "    },\n";
  config += "  },\n";
  config += "};\n";

  return config;
}

/**
 * Generate Figma tokens JSON
 */
export function generateFigmaTokens(
  issues: ContrastIssue[],
  suggestions: Map<number, ColorSuggestion>
): string {
  const tokens = {
    "Color Fixes": {} as Record<
      string,
      {
        value: string;
        type: string;
        description: string;
      }
    >,
  };

  let colorIndex = 1;

  issues.forEach((issue, index) => {
    const suggestion = suggestions.get(index);
    if (!suggestion) return;

    if (issue.foreground !== suggestion.foreground) {
      const tokenName = `Text Fix ${colorIndex}`;
      tokens["Color Fixes"][tokenName] = {
        value: suggestion.foreground,
        type: "color",
        description: `Text color fix for issue ${index + 1} (${suggestion.ratio.toFixed(2)}:1 contrast)`,
      };
      colorIndex++;
    }

    if (issue.background !== suggestion.background) {
      const tokenName = `Background Fix ${colorIndex}`;
      tokens["Color Fixes"][tokenName] = {
        value: suggestion.background,
        type: "color",
        description: `Background color fix for issue ${index + 1} (${suggestion.ratio.toFixed(2)}:1 contrast)`,
      };
      colorIndex++;
    }
  });

  return JSON.stringify(tokens, null, 2);
}

/**
 * Generate HTML report with color swatches
 */
export function generateHTMLReport(
  report: AccessibilityReport,
  suggestions: Map<number, ColorSuggestion>
): string {
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Color Contrast Audit Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    .header {
      background: white;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 20px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .issue {
      background: white;
      padding: 20px;
      margin-bottom: 20px;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .color-pair {
      display: flex;
      gap: 10px;
      margin: 10px 0;
      align-items: center;
    }
    .color-swatch {
      width: 60px;
      height: 60px;
      border-radius: 4px;
      border: 1px solid #ddd;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 12px;
      font-weight: bold;
      color: #666;
    }
    .improvement {
      color: #22C55E;
      font-weight: bold;
    }
    .wcag-badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: bold;
      margin-left: 10px;
    }
    .wcag-aaa {
      background: #D1FAE5;
      color: #065F46;
    }
    .wcag-aa {
      background: #FEF3C7;
      color: #78350F;
    }
    .summary {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      margin-bottom: 20px;
    }
    .summary-card {
      background: white;
      padding: 15px;
      border-radius: 8px;
      text-align: center;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .summary-card h3 {
      margin: 0 0 10px 0;
      color: #666;
      font-size: 14px;
    }
    .summary-card .number {
      font-size: 32px;
      font-weight: bold;
      color: #0a7ea4;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Color Contrast Audit Report</h1>
    <p>Generated by Site Auditor Pro on ${new Date().toLocaleString()}</p>
  </div>

  <div class="summary">
    <div class="summary-card">
      <h3>Total Issues</h3>
      <div class="number">${report.contrastIssues.length}</div>
    </div>
    <div class="summary-card">
      <h3>WCAG AAA Compliant</h3>
      <div class="number">${report.wcagAAA.pass}</div>
    </div>
    <div class="summary-card">
      <h3>WCAG AA Compliant</h3>
      <div class="number">${report.wcagAA.pass}</div>
    </div>
    <div class="summary-card">
      <h3>Accessibility Score</h3>
      <div class="number">${Math.round(report.wcagAAA.percentage)}%</div>
    </div>
  </div>
`;

  report.contrastIssues.forEach((issue, index) => {
    const suggestion = suggestions.get(index);

    html += `
  <div class="issue">
    <h3>Issue ${index + 1}: ${issue.element || "Unknown"}</h3>
    <p><strong>Text Size:</strong> ${issue.textSize}</p>
    
    <h4>Original Colors</h4>
    <div class="color-pair">
      <div class="color-swatch" style="background: ${issue.foreground}; color: ${issue.background};">
        Text
      </div>
      <div>
        <strong>Foreground:</strong> ${issue.foreground}<br>
        <strong>Background:</strong> ${issue.background}<br>
        <strong>Contrast Ratio:</strong> ${issue.ratio.toFixed(2)}:1
      </div>
    </div>
`;

    if (suggestion) {
      html += `
    <h4>Suggested Colors</h4>
    <div class="color-pair">
      <div class="color-swatch" style="background: ${suggestion.background}; color: ${suggestion.foreground};">
        Text
      </div>
      <div>
        <strong>Foreground:</strong> ${suggestion.foreground}<br>
        <strong>Background:</strong> ${suggestion.background}<br>
        <strong>Contrast Ratio:</strong> ${suggestion.ratio.toFixed(2)}:1
        <span class="wcag-badge wcag-${suggestion.wcagLevel === "AAA" ? "aaa" : "aa"}">
          WCAG ${suggestion.wcagLevel}
        </span>
        <div class="improvement">+${suggestion.improvement}% improvement</div>
      </div>
    </div>
`;
    }

    html += `
  </div>
`;
  });

  html += `
</body>
</html>
`;

  return html;
}

/**
 * Export audit results in specified format
 */
export function exportAudit(
  report: AccessibilityReport,
  suggestions: Map<number, ColorSuggestion>,
  format: ExportOptions["format"]
): string {
  switch (format) {
    case "css":
      return generateCSSSnippet(report.contrastIssues, suggestions);
    case "scss":
      return generateSCSSVariables(report.contrastIssues, suggestions);
    case "json":
      return generateDesignTokens(report.contrastIssues, suggestions);
    case "tailwind":
      return generateTailwindConfig(report.contrastIssues, suggestions);
    case "figma":
      return generateFigmaTokens(report.contrastIssues, suggestions);
    default:
      return generateCSSSnippet(report.contrastIssues, suggestions);
  }
}

/**
 * Create downloadable file blob
 */
export function createDownloadBlob(content: string, format: ExportOptions["format"]): Blob {
  const mimeTypes: Record<ExportOptions["format"], string> = {
    css: "text/css",
    scss: "text/x-scss",
    json: "application/json",
    tailwind: "text/javascript",
    figma: "application/json",
  };

  return new Blob([content], { type: mimeTypes[format] });
}

/**
 * Generate filename for export
 */
export function generateFilename(format: ExportOptions["format"]): string {
  const timestamp = new Date().toISOString().split("T")[0];
  const extensions: Record<ExportOptions["format"], string> = {
    css: "css",
    scss: "scss",
    json: "json",
    tailwind: "js",
    figma: "json",
  };

  return `color-fixes-${timestamp}.${extensions[format]}`;
}
