import { describe, it, expect } from "vitest";
import {
  generateCSSSnippet,
  generateSCSSVariables,
  generateDesignTokens,
  generateTailwindConfig,
  generateFigmaTokens,
  generateHTMLReport,
  exportAudit,
  createDownloadBlob,
  generateFilename,
  type ExportOptions,
} from "./batch-export";
import { type ContrastIssue, type AccessibilityReport } from "./contrast-analyzer";
import { type ColorSuggestion } from "./color-suggester";

describe("Batch Export", () => {
  const mockIssues: ContrastIssue[] = [
    {
      element: ".text-muted",
      foreground: "#687076",
      background: "#ffffff",
      ratio: 4.5,
      wcagAA: true,
      wcagAAA: false,
      textSize: "normal",
      recommendation: "Darken the text color",
    },
    {
      element: ".button-primary",
      foreground: "#0a7ea4",
      background: "#f5f5f5",
      ratio: 5.2,
      wcagAA: true,
      wcagAAA: false,
      textSize: "normal",
      recommendation: "Increase contrast",
    },
  ];

  const mockSuggestions = new Map<number, ColorSuggestion>([
    [
      0,
      {
        foreground: "#3B3B3B",
        background: "#ffffff",
        ratio: 9.5,
        wcagLevel: "AAA",
        strategy: "darken-fg",
        improvement: 111,
        preview: {
          original: { fg: "#687076", bg: "#ffffff", ratio: 4.5 },
          suggested: { fg: "#3B3B3B", bg: "#ffffff", ratio: 9.5 },
        },
      },
    ],
    [
      1,
      {
        foreground: "#003366",
        background: "#f5f5f5",
        ratio: 8.2,
        wcagLevel: "AAA",
        strategy: "darken-fg",
        improvement: 58,
        preview: {
          original: { fg: "#0a7ea4", bg: "#f5f5f5", ratio: 5.2 },
          suggested: { fg: "#003366", bg: "#f5f5f5", ratio: 8.2 },
        },
      },
    ],
  ]);

  const mockReport: AccessibilityReport = {
    url: "https://example.com",
    timestamp: Date.now(),
    totalElements: 100,
    contrastIssues: mockIssues,
    wcagAA: { pass: 95, fail: 5, percentage: 95 },
    wcagAAA: { pass: 80, fail: 20, percentage: 80 },
    summary: "Most elements pass WCAG AA",
  };

  describe("generateCSSSnippet", () => {
    it("should generate CSS with comments", () => {
      const css = generateCSSSnippet(mockIssues, mockSuggestions, {
        includeComments: true,
      });

      expect(css).toContain("Generated by Site Auditor Pro");
      expect(css).toContain(".text-muted");
      expect(css).toContain("color:");
      expect(css).toContain("#3B3B3B");
    });

    it("should generate minified CSS", () => {
      const css = generateCSSSnippet(mockIssues, mockSuggestions, { minify: true });

      expect(css).not.toContain("\n");
      expect(css).not.toContain("/*");
    });

    it("should include color values", () => {
      const css = generateCSSSnippet(mockIssues, mockSuggestions);

      expect(css).toContain("#3B3B3B");
      expect(css).toContain("#003366");
    });

    it("should handle missing suggestions gracefully", () => {
      const emptySuggestions = new Map<number, ColorSuggestion>();
      const css = generateCSSSnippet(mockIssues, emptySuggestions);

      expect(css).toBeDefined();
    });
  });

  describe("generateSCSSVariables", () => {
    it("should generate SCSS variables", () => {
      const scss = generateSCSSVariables(mockIssues, mockSuggestions);

      expect(scss).toContain("$text-color");
      expect(scss).toContain("#3B3B3B");
      expect(scss).toContain("//");
    });

    it("should include original color comments", () => {
      const scss = generateSCSSVariables(mockIssues, mockSuggestions);

      expect(scss).toContain("#687076");
    });
  });

  describe("generateDesignTokens", () => {
    it("should generate valid JSON", () => {
      const json = generateDesignTokens(mockIssues, mockSuggestions);
      const parsed = JSON.parse(json);

      expect(parsed).toBeDefined();
      expect(parsed.colorContrast).toBeDefined();
      expect(parsed.colorContrast.fixes).toBeInstanceOf(Array);
    });

    it("should include all required fields", () => {
      const json = generateDesignTokens(mockIssues, mockSuggestions);
      const parsed = JSON.parse(json);

      const fix = parsed.colorContrast.fixes[0];
      expect(fix.id).toBeDefined();
      expect(fix.selector).toBeDefined();
      expect(fix.original).toBeDefined();
      expect(fix.suggested).toBeDefined();
      expect(fix.wcagLevel).toBeDefined();
      expect(fix.improvement).toBeDefined();
    });

    it("should include timestamp", () => {
      const json = generateDesignTokens(mockIssues, mockSuggestions);
      const parsed = JSON.parse(json);

      expect(parsed.generated).toBeDefined();
      expect(new Date(parsed.generated)).toBeInstanceOf(Date);
    });
  });

  describe("generateTailwindConfig", () => {
    it("should generate valid JavaScript", () => {
      const config = generateTailwindConfig(mockIssues, mockSuggestions);

      expect(config).toContain("module.exports");
      expect(config).toContain("theme");
      expect(config).toContain("colors");
    });

    it("should include color values", () => {
      const config = generateTailwindConfig(mockIssues, mockSuggestions);

      expect(config).toContain("#3B3B3B");
      expect(config).toContain("#003366");
    });

    it("should have proper syntax", () => {
      const config = generateTailwindConfig(mockIssues, mockSuggestions);

      expect(config).toContain("'");
      expect(config).toContain(":");
    });
  });

  describe("generateFigmaTokens", () => {
    it("should generate valid JSON", () => {
      const json = generateFigmaTokens(mockIssues, mockSuggestions);
      const parsed = JSON.parse(json);

      expect(parsed).toBeDefined();
      expect(parsed["Color Fixes"]).toBeDefined();
    });

    it("should include color values", () => {
      const json = generateFigmaTokens(mockIssues, mockSuggestions);
      const parsed = JSON.parse(json);

      const fixes = Object.values(parsed["Color Fixes"]) as Array<{
        value: string;
        type: string;
      }>;
      expect(fixes.length).toBeGreaterThan(0);
      expect(fixes[0].value).toMatch(/^#[0-9a-f]{6}$/i);
    });

    it("should include descriptions", () => {
      const json = generateFigmaTokens(mockIssues, mockSuggestions);
      const parsed = JSON.parse(json);

      const fixes = Object.values(parsed["Color Fixes"]) as Array<{
        description: string;
      }>;
      expect(fixes[0].description).toBeDefined();
    });
  });

  describe("generateHTMLReport", () => {
    it("should generate valid HTML", () => {
      const html = generateHTMLReport(mockReport, mockSuggestions);

      expect(html).toContain("<!DOCTYPE html>");
      expect(html).toContain("</html>");
      expect(html).toContain("<style>");
    });

    it("should include summary statistics", () => {
      const html = generateHTMLReport(mockReport, mockSuggestions);

      expect(html).toContain("Total Issues");
      expect(html).toContain("WCAG AAA");
      expect(html).toContain("WCAG AA");
    });

    it("should include color swatches", () => {
      const html = generateHTMLReport(mockReport, mockSuggestions);

      expect(html).toContain("color-swatch");
      expect(html).toContain("#3B3B3B");
    });

    it("should include contrast ratios", () => {
      const html = generateHTMLReport(mockReport, mockSuggestions);

      expect(html).toContain("Contrast Ratio");
      // Check for ratio format (may be 9.5:1 or similar)
      expect(html).toMatch(/\d+\.\d+:1/);
    });

    it("should include improvement percentages", () => {
      const html = generateHTMLReport(mockReport, mockSuggestions);

      expect(html).toContain("improvement");
    });
  });

  describe("exportAudit", () => {
    it("should export as CSS", () => {
      const result = exportAudit(mockReport, mockSuggestions, "css");

      expect(result).toContain("color:");
      expect(result).toContain("#3B3B3B");
    });

    it("should export as SCSS", () => {
      const result = exportAudit(mockReport, mockSuggestions, "scss");

      expect(result).toContain("$");
      expect(result).toContain("#3B3B3B");
    });

    it("should export as JSON", () => {
      const result = exportAudit(mockReport, mockSuggestions, "json");
      const parsed = JSON.parse(result);

      expect(parsed.colorContrast).toBeDefined();
    });

    it("should export as Tailwind", () => {
      const result = exportAudit(mockReport, mockSuggestions, "tailwind");

      expect(result).toContain("module.exports");
    });

    it("should export as Figma tokens", () => {
      const result = exportAudit(mockReport, mockSuggestions, "figma");
      const parsed = JSON.parse(result);

      expect(parsed["Color Fixes"]).toBeDefined();
    });
  });

  describe("createDownloadBlob", () => {
    it("should create CSS blob", () => {
      const blob = createDownloadBlob("body { color: red; }", "css");

      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe("text/css");
    });

    it("should create JSON blob", () => {
      const blob = createDownloadBlob('{"test": "data"}', "json");

      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe("application/json");
    });

    it("should create SCSS blob", () => {
      const blob = createDownloadBlob("$color: red;", "scss");

      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe("text/x-scss");
    });

    it("should preserve content", () => {
      const content = "test content";
      const blob = createDownloadBlob(content, "css");

      expect(blob.size).toBeGreaterThan(0);
    });
  });

  describe("generateFilename", () => {
    it("should generate CSS filename", () => {
      const filename = generateFilename("css");

      expect(filename).toContain("color-fixes");
      expect(filename).toMatch(/\.css$/);
    });

    it("should generate SCSS filename", () => {
      const filename = generateFilename("scss");

      expect(filename).toMatch(/\.scss$/);
    });

    it("should generate JSON filename", () => {
      const filename = generateFilename("json");

      expect(filename).toMatch(/\.json$/);
    });

    it("should include date", () => {
      const filename = generateFilename("css");
      const today = new Date().toISOString().split("T")[0];

      expect(filename).toContain(today);
    });

    it("should generate unique filenames for different formats", () => {
      const cssName = generateFilename("css");
      const jsonName = generateFilename("json");

      expect(cssName).not.toBe(jsonName);
    });
  });

  describe("Real-world scenarios", () => {
    it("should handle multiple contrast issues", () => {
      const css = generateCSSSnippet(mockIssues, mockSuggestions);

      expect(css).toContain(".text-muted");
      expect(css).toContain(".button-primary");
    });

    it("should generate complete export package", () => {
      const css = exportAudit(mockReport, mockSuggestions, "css");
      const json = exportAudit(mockReport, mockSuggestions, "json");
      const html = generateHTMLReport(mockReport, mockSuggestions);

      expect(css.length).toBeGreaterThan(0);
      expect(json.length).toBeGreaterThan(0);
      expect(html.length).toBeGreaterThan(0);
    });

    it("should create downloadable artifacts", () => {
      const css = exportAudit(mockReport, mockSuggestions, "css");
      const blob = createDownloadBlob(css, "css");
      const filename = generateFilename("css");

      expect(blob).toBeInstanceOf(Blob);
      expect(filename).toContain("color-fixes");
    });
  });
});
