/**
 * Bootstrap Theme Exporter
 * Generates Bootstrap-compatible CSS for customized themes
 */

export interface BootstrapTheme {
  light: Map<string, string>;
  dark: Map<string, string>;
}

/**
 * Generate Bootstrap theme CSS
 */
export function generateBootstrapThemeCSS(theme: BootstrapTheme): string {
  const lightVars = Array.from(theme.light.entries());
  const darkVars = Array.from(theme.dark.entries());
  
  let css = `/* Bootstrap Custom Theme */\n/* Generated by Site Auditor Pro */\n\n`;
  
  // Light mode (default)
  if (lightVars.length > 0) {
    css += `:root {\n`;
    lightVars.forEach(([name, value]) => {
      css += `  ${name}: ${value};\n`;
    });
    css += `}\n\n`;
  }
  
  // Dark mode
  if (darkVars.length > 0) {
    css += `[data-bs-theme="dark"] {\n`;
    darkVars.forEach(([name, value]) => {
      css += `  ${name}: ${value};\n`;
    });
    css += `}\n`;
  }
  
  return css;
}

/**
 * Generate separate light and dark theme files
 */
export function generateSeparateThemes(theme: BootstrapTheme): {
  light: string;
  dark: string;
} {
  const lightVars = Array.from(theme.light.entries());
  const darkVars = Array.from(theme.dark.entries());
  
  let lightCSS = `/* Bootstrap Light Theme */\n/* Generated by Site Auditor Pro */\n\n:root {\n`;
  lightVars.forEach(([name, value]) => {
    lightCSS += `  ${name}: ${value};\n`;
  });
  lightCSS += `}\n`;
  
  let darkCSS = `/* Bootstrap Dark Theme */\n/* Generated by Site Auditor Pro */\n\n[data-bs-theme="dark"] {\n`;
  darkVars.forEach(([name, value]) => {
    darkCSS += `  ${name}: ${value};\n`;
  });
  darkCSS += `}\n`;
  
  return { light: lightCSS, dark: darkCSS };
}

/**
 * Download CSS file (web only)
 */
export function downloadCSS(css: string, filename: string) {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    console.warn('Download is only available in web environment');
    return;
  }
  
  const blob = new Blob([css], { type: 'text/css' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy CSS to clipboard (web only)
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof navigator === 'undefined' || !navigator.clipboard) {
    console.warn('Clipboard is only available in web environment');
    return false;
  }
  
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
    return false;
  }
}

/**
 * Extract Bootstrap variables from palette
 */
export function extractBootstrapVariables(
  variables: Array<{ name: string; value: string }>
): Map<string, string> {
  const bootstrapVars = new Map<string, string>();
  
  variables.forEach(v => {
    if (v.name.startsWith('--bs-')) {
      bootstrapVars.set(v.name, v.value);
    }
  });
  
  return bootstrapVars;
}

/**
 * Get common Bootstrap color variables for display
 */
export function getBootstrapColorCategories() {
  return {
    'Body': [
      '--bs-body-bg',
      '--bs-body-color',
      '--bs-body-bg-rgb',
      '--bs-body-color-rgb',
    ],
    'Text': [
      '--bs-heading-color',
      '--bs-emphasis-color',
      '--bs-secondary-color',
      '--bs-tertiary-color',
    ],
    'Links': [
      '--bs-link-color',
      '--bs-link-hover-color',
      '--bs-link-color-rgb',
    ],
    'Borders': [
      '--bs-border-color',
      '--bs-border-color-translucent',
    ],
    'Theme Colors': [
      '--bs-primary',
      '--bs-secondary',
      '--bs-success',
      '--bs-danger',
      '--bs-warning',
      '--bs-info',
      '--bs-light',
      '--bs-dark',
    ],
  };
}
